#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service both

PROCESS_NAME="whiteboard"
check_container_initialized

transform_file_var \
                    JWT_SECRET_KEY \
                    NEXTCLOUD_URL

export BACKUP_DIR=${BACKUP_PATH}
export NODE_ENV=production
export NEXTCLOUD_URL=${NEXTCLOUD_URL}
export JWT_SECRET_KEY=${JWT_SECRET_KEY}

cd /app

liftoff

print_start "Starting Nextcloud Whiteboard Collaboration Server"
s6-setuidgid ncwhiteboard \
                            npm \
                                run \
                                    server:start